version: '3.8'
services:
  backend:
    image: stasdevgunp/neuro_app:latest
    environment:
    - MY_ENV_VAR = value 
  nginx: 
    image: nginx-latest
    ports:
    - "80:80"
    volumes:
      - ./default.conf:etc/nginx/conf.d/default.conf:ro
      - nginx_logs: /var/log/nginx
    depends_on:
    - backend
volumes:
  - nginx_logs: 

