version: '3.8'

services:
  ner_api:
    image: stasdevgunp/neuro_test:latest
    container_name : ne_api_conrtainer
    restart: always
    volumes: 
    - ./app/data:/app/data
    expose:
      - '8000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    container_name : ner_ngingx_proxy
    ports: 
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ner_api